apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "iran-accountability.fullname" . }}-secrets
  labels:
    {{- include "iran-accountability.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ include "iran-accountability.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: internal-admin-token
      remoteRef:
        key: platform/iran-accountability
        property: internal_admin_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
