apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: iran-accountability-build-and-deploy-template
spec:
  entrypoint: build-and-deploy-dag
  arguments:
    parameters:
      - name: repository
        value: "git@github.com:iRavenIO/ForFreeIranAccountability.git"
      - name: branch
        value: main
      - name: commit
      - name: docker-tag
      - name: namespace
  templates:
    - name: build-and-deploy-dag
      dag:
        tasks:
          - name: build-amd64
            templateRef:
              name: iran-accountability-build-template
              template: build-image
            arguments:
              parameters:
                - name: docker-tag
                  value: "{{workflow.parameters.docker-tag}}"
                - name: arch
                  value: amd64

          - name: create-manifest
            depends: build-amd64
            templateRef:
              name: iran-accountability-build-template
              template: create-manifest-list
            arguments:
              parameters:
                - name: docker-tag
                  value: "{{workflow.parameters.docker-tag}}"

          - name: update-version
            depends: create-manifest
            templateRef:
              name: iran-accountability-git-template
              template: update-version
            arguments:
              parameters:
                - name: docker-tag
                  value: "{{workflow.parameters.docker-tag}}"
                - name: repository
                  value: "{{workflow.parameters.repository}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
