apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: iran-accountability-git-template
spec:
  templates:
    - name: update-version
      retryStrategy:
        limit: 3
        backoff:
          duration: "10s"
          factor: 2
      inputs:
        parameters:
          - name: docker-tag
          - name: repository
          - name: branch
      container:
        image: harbor-registry.tail02a6d.ts.net/library/alpine-ci:3.18
        command: ["/bin/sh", "-c"]
        args:
          - |
            SSH_REPO="{{inputs.parameters.repository}}"
            REPO_URL=$(echo "$SSH_REPO" | sed 's|git@github.com:|https://x-access-token:'"${GITHUB_TOKEN}"'@github.com/|')
            git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"

            echo "Cloning repository for version update..."
            rm -rf /tmp/repo
            git clone "$REPO_URL" /tmp/repo || { echo "Failed to clone repository"; exit 1; }
            cd /tmp/repo || { echo "Failed to change to cloned repository"; exit 1; }

            DOCKER_TAG="{{inputs.parameters.docker-tag}}"
            DOCKER_TAG=$(echo "$DOCKER_TAG" | sed 's|refs/tags/||; s|refs/heads/||')

            echo "Updating version-values.yaml with tag: $DOCKER_TAG"
            cd .deployment/accountability || { echo "Failed to change to .deployment/accountability directory"; exit 1; }
            sed -i "s/tag: \".*\"/tag: \"$DOCKER_TAG\"/" version-values.yaml
            echo "Updated version-values.yaml content:"
            cat version-values.yaml

            git config user.email "ci@voice.forfreeiran.com"
            git config user.name "ForFreeIran CI"
            git add version-values.yaml
            git commit -m "Deploy version $DOCKER_TAG to Harbor"
            git push -f origin {{inputs.parameters.branch }} || { echo "Failed to push to repository"; exit 1; }
            echo "Successfully updated and pushed version $DOCKER_TAG"
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
